<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AssemblyName>HelloPlugin</AssemblyName>
    <RootNamespace>Hello</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../dotnet/Falcon.PluginAPI/Falcon.PluginAPI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="plugin.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
